openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API xác thực người dùng

paths:
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Đăng nhập
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: secret
      responses:
        '200':
          description: Đăng nhập thành công, trả về access token và cookie refresh_token
        '404':
          description: Email hoặc mật khẩu không đúng

  /api/v1/auth/logout:
    post:
      tags:
        - Auth
      summary: Đăng xuất
      responses:
        '200':
          description: Đăng xuất thành công
        '400':
          description: Chưa có refresh Token

  /api/v1/auth/refreshtoken:
    post:
      tags:
        - Auth
      summary: Cấp mới access token từ refresh token
      responses:
        '200':
          description: Trả về access token mới
        '404':
          description: Token không hợp lệ hoặc đã bị xoá
