openapi: 3.0.0
info:
  title: Language API
  version: 1.0.0
  description: API quản lý ngôn ngữ
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /language:
    get:
      tags:
        - Languages
      summary: Danh sách ngôn ngữ
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Danh sách ngôn ngữ
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  status:
                    type: integer
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      rows:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            lang_code:
                              type: string
                            lang_name:
                              type: string
                            created_at:
                              type: string
                              format: date-time
                            updated_at:
                              type: string
                              format: date-time
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                          page:
                            type: integer
                          limit:
                            type: integer
                          totalPages:
                            type: integer

  /language/{id}:
    get:
      tags:
        - Languages
      summary: Lấy ngôn ngữ theo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Thông tin ngôn ngữ
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      lang_code:
                        type: string
                        example: "vi"
                      lang_name:
                        type: string
                        example: "Tiếng Việt"
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-10-24T10:34:28.000Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-10-24T10:34:28.000Z"
        '404':
          description: Không tồn tại ngôn ngữ này
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "Không tồn tại ngôn ngữ này"

  /language/create:
    post:
      tags:
        - Languages
      summary: Tạo ngôn ngữ
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - lang_code
                - lang_name
              properties:
                lang_code:
                  type: string
                lang_name:
                  type: string
      responses:
        '200':
          description: Tạo thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 4
                      lang_code:
                        type: string
                        example: "cn"
                      lang_name:
                        type: string
                        example: "China"
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-11-02T03:17:04.634Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-11-02T03:17:04.635Z"
        '422':
          description: Thiếu dữ liệu
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 422
                  message:
                    type: string
                    example: "chưa truyền ID"

  /language/edit/{id}:
    put:
      tags:
        - Languages
      summary: Cập nhật ngôn ngữ
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lang_code:
                  type: string
                lang_name:
                  type: string
      responses:
        '200':
          description: Sửa thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: string
                    example: "Đã sửa thành công !"
        '404':
          description: Không tồn tại ngôn ngữ
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 422
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        msg:
                          type: string
  /language/delete/{id}:
    delete:
      tags:
        - Languages
      summary: Xoá ngôn ngữ
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Xoá thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Xóa thành công"
                  data:
                    type: object
                    additionalProperties: {}
        '404':
          description: Không tồn tại ngôn ngữ
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "Không tìm thấy category"
