openapi: 3.0.0
info:
  title: Post API
  version: 1.0.0
  description: API quản lý bài viết

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
paths:
  /post:
    get:
      tags:
        - Posts
      summary: Danh sách bài viết
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
        - in: query
          name: category_id
          schema:
            type: integer
        - in: query
          name: tag_id
          schema:
            type: integer
        - in: query
          name: user_id
          schema:
            type: integer
        - in: query
          name: lang_id
          schema:
            type: integer
        - in: query
          name: status
          schema:
            type: string
        - in: query
          name: featured
          schema:
            type: boolean
      responses:
        '200':
          description: Danh sách bài viết
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      rows:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 10
                            title:
                              type: string
                              example: "Bài viết mẫu"
                            slug:
                              type: string
                              example: "bai-viet-mau"
                            thumbnail:
                              type: string
                              example: "img/default-post.png"
                            content:
                              type: string
                              example: "Nội dung bài viết ..."
                            status:
                              type: string
                              example: "published"
                            featured:
                              type: boolean
                              example: false
                            created_at:
                              type: string
                              format: date-time
                              example: "2025-10-30T08:44:07.000Z"
                            updated_at:
                              type: string
                              format: date-time
                              example: "2025-10-30T10:35:17.000Z"
                            User:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1
                                username:
                                  type: string
                                  example: "admin"
                            categories:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                    example: 1
                                  cat_name:
                                    type: string
                                    example: "Technology"
                            tags:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: integer
                                    example: 1
                                  name:
                                    type: string
                                    example: "AI"
                            Language:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 1
                                lang_name:
                                  type: string
                                  example: "Tiếng Việt"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 9
                          page:
                            type: integer
                            example: 1
                          limit:
                            type: integer
                            example: 10
                          totalPages:
                            type: integer
                            example: 1

  /post/{id}:
    get:
      tags:
        - Posts
      summary: Lấy bài viết theo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Thông tin bài viết
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 10
                      title:
                        type: string
                        example: "Bài viết mẫu"
                      slug:
                        type: string
                        example: "bai-viet-mau"
                      thumbnail:
                        type: string
                        example: "img/default-post.png"
                      content:
                        type: string
                        example: "Nội dung bài viết ..."
                      status:
                        type: string
                        example: "published"
                      featured:
                        type: boolean
                        example: false
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T08:44:07.000Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T08:44:07.000Z"
        '404':
          description: Không tồn tại bài viết

  /post/create:
    post:
      tags:
        - Posts
      summary: Tạo bài viết
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - category
                - user_id
              properties:
                title:
                  type: string
                thumbnail:
                  type: string
                featured:
                  type: boolean
                status:
                  type: string
                  example: draft
                content:
                  type: string 
                category:
                  type: integer
                user_id:
                  type: integer
                tags:
                  type: integer
                lang_id:
                  type: integer
      responses:
        '200':
          description: Tạo thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 10
                      title:
                        type: string
                        example: "Bài viết mẫu"
                      slug:
                        type: string
                        example: "bai-viet-mau"
                      thumbnail:
                        type: string
                        example: "img/default-post.png"
                      content:
                        type: string
                        example: "Nội dung bài viết ..."
                      status:
                        type: string
                        example: "draft"
                      featured:
                        type: boolean
                        example: false
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T08:44:07.000Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T08:44:07.000Z"
        '422':
          description: Validation error

  /post/edit/{id}:
    put:
      tags:
        - Posts
      summary: Cập nhật bài viết
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                thumbnail:
                  type: string
                content:
                  type: string
                category:
                  type: integer
                tags:
                  type: integer
                lang_id:
                  type: integer
      responses:
        '200':
          description: Sửa thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 10
                      title:
                        type: string
                        example: "Tiêu đề đã cập nhật"
                      slug:
                        type: string
                        example: "tieu-de-da-cap-nhat"
                      thumbnail:
                        type: string
                        example: "img/default-post.png"
                      content:
                        type: string
                        example: "Nội dung đã cập nhật ..."
                      user_id:
                        type: integer
                        example: 3
                      status:
                        type: string
                        example: "published"
                      featured:
                        type: boolean
                        example: true
                      lang_id:
                        type: integer
                        example: 1
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T08:44:07.000Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T08:44:07.000Z"
        '404':
          description: Không tồn tại bài viết

  /post/delete/{id}:
    delete:
      tags:
        - Posts
      summary: Xoá bài viết
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Xoá thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 10
        '404':
          description: Không tồn tại bài viết
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: "Không tồn tại bài viết"
