openapi: 3.0.0
info:
  title: Upload API
  version: 1.0.0
  description: API upload file
paths:
  /upload:
    post:
      tags:
        - Upload
      summary: Upload file (image)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Upload thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: File uploaded successfully
                  data:
                    type: object
                    properties:
                      file:
                        type: object
                      url:
                        type: string
                        example: http://localhost:3000/uploads/file-123.png
        '401':
          description: Unauthorized
