openapi: 3.0.0
info:
  title: Public API
  version: 1.0.0
  description: Client Public API.

paths:
  /public/category:
    get:
      tags:
        - Public Client API
      summary: danh sách tất cả danh mục puclic
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Danh sách categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      rows:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 9
                            cat_name:
                              type: string
                              example: "Chính Trị"
                            thumbnail:
                              type: string
                              example: "img/default-category.png"
                            description:
                              type: string
                              example: "Tin tức về Trump"
                            cat_slug:
                              type: string
                              example: "chnh-tr"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 9
                          page:
                            type: integer
                            example: 1
                          limit:
                            type: integer
                            example: 10
                          totalPages:
                            type: integer
                            example: 1
  /public/category/:id:
    get:
      tags:
        - Public Client API
      summary: Lấy thông tin danh mục và tất cả posts trong danh mục đó
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Thông tin category và posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: "Travel"
                      thumbnail:
                        type: string
                        nullable: true
                        example: null
                      description:
                        type: string
                        nullable: true
                        example: null
                      slug:
                        type: string
                        nullable: true
                        example: null
                      posts:
                        type: object
                        properties:
                          rows:
                            type: array
                            items:
                              type: object
                              properties:
                                id:
                                  type: integer
                                  example: 109
                                title:
                                  type: string
                                  example: "get sss s one more time 233"
                                content:
                                  type: string
                                  example: "CoS LAP  SLAPSL APSLAPok fried EGGS."
                                slug:
                                  type: string
                                  example: "get-sss-s-one-more-time-233"
                          pagination:
                            type: object
                            properties:
                              total:
                                type: integer
                                example: 7
                              page:
                                type: integer
                                example: 1
                              limit:
                                type: integer
                                example: 10
                              totalPages:
                                type: integer
                                example: 1
  /public/post:
    get:
      tags:
        - Public Client API
      summary: Danh sách tất cả bài viết public
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Danh sách posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      rows:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 109
                            title:
                              type: string
                              example: "get sss s one more time 233"
                            content:
                              type: string
                              example: "CoS LAP  SLAPSL APSLAPok fried EGGS."
                            slug:
                              type: string
                              example: "get-sss-s-one-more-time-233"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 109
                          page:
                            type: integer
                            example: 1
                          limit:
                            type: integer
                            example: 10
                          totalPages:
                            type: integer
                            example: 11
  /public/post/:id:
    get:
      tags:
        - Public Client API
      summary: Lấy thông tin chi tiết một bài viết
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Thông tin chi tiết bài viết
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 109
                      thumbnail:
                        type: string
                        example: "img/default-thumbnail.jpg"
                      slug:
                        type: string
                        example: "get-sss-s-one-more-time-233"
                      title:
                        type: string
                        example: "get sss s one more time 233"
                      content:
                        type: string
                        example: "CoS LAP  SLAPSL APSLAPok fried EGGS."
                      status:
                        type: string
                        example: "draft"
                      featured:
                        type: boolean
                        example: false
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T10:35:17.000Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-10-30T10:35:17.000Z"
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          username:
                            type: string
                            example: "admin"
                      categories:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: "Technology"
                      tags:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: "AI"
                      language:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          lang_name:
                            type: string
                            example: "Tiếng Việt"
  /public/post/comment/:id:
    get:
      tags:
        - Public Client API
      summary: Danh sách comment theo bài viết
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: limit
          schema:
            type: integer
      responses:
        '200':
          description: Danh sách comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "ok"
                  data:
                    type: object
                    properties:
                      rows:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            content:
                              type: string
                              example: "Great article! Very informative."
                            parent_id:
                              type: integer
                              nullable: true
                              example: null
                            created_at:
                              type: string
                              format: date-time
                              example: "2025-10-24T10:34:28.000Z"
                            updated_at:
                              type: string
                              format: date-time
                              example: "2025-10-24T10:34:28.000Z"
                            user:
                              type: object
                              properties:
                                username:
                                  type: string
                                  example: "moderator"
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 1
                          page:
                            type: integer
                            example: 1
                          limit:
                            type: integer
                            example: 10
                          totalPages:
                            type: integer
                            example: 1




